"""System prompts and output schemas for the anomaly analysis agent."""

from pydantic import BaseModel, Field


# ═══════════════════════════════════════════════════════════════════════════════
# STRUCTURED OUTPUT SCHEMA
# ═══════════════════════════════════════════════════════════════════════════════


class ImpactMetrics(BaseModel):
    """Quantitative metrics showing the incident's impact."""

    volume_increase_pct: float = Field(
        description="Percentage increase in ticket volume compared to baseline"
    )
    primary_priority: str = Field(
        description="The dominant priority level of tickets (e.g., 'high', 'critical')"
    )
    primary_queue: str = Field(
        description="The most affected queue/department"
    )
    primary_type: str = Field(
        description="The dominant ticket type (e.g., 'Incident', 'Problem')"
    )


class IncidentReport(BaseModel):
    """Structured incident report generated by the anomaly analysis agent."""

    title: str = Field(
        description="A concise title for the incident (e.g., 'Login Service Outage')"
    )

    executive_summary: str = Field(
        description="A 1-2 sentence summary of what happened and its impact"
    )

    root_cause: str = Field(
        description="The most likely root cause based on ticket content analysis"
    )

    impact_metrics: ImpactMetrics = Field(
        description="Key metrics showing the impact"
    )

    affected_services: list[str] = Field(
        description="List of services or areas affected (e.g., ['Login', 'Authentication', 'Mobile App'])"
    )

    customer_sentiment: str = Field(
        description="Overall customer sentiment derived from ticket samples (e.g., 'Frustrated', 'Confused', 'Urgent')"
    )

    sample_complaints: list[str] = Field(
        description="3-5 representative quotes or paraphrased complaints from customers"
    )

    recommendations: list[str] = Field(
        description="2-3 actionable recommendations for the engineering/support team"
    )


# ═══════════════════════════════════════════════════════════════════════════════
# SYSTEM PROMPT
# ═══════════════════════════════════════════════════════════════════════════════


SYSTEM_PROMPT = """You are an expert Site Reliability Engineer (SRE) and Support Analyst.

Your job is to analyze anomalies detected by automated monitoring systems and produce
clear, actionable incident reports for engineering and support teams.

## Your Analysis Process

1. **Gather Statistics**: Use fetch_ticket_stats to understand the volume and distribution
   changes compared to baseline. Look for significant shifts in priority, type, queues, or tags.

2. **Read Samples**: Use fetch_ticket_samples to read actual customer complaints.
   Look for patterns in what customers are describing - common error messages, affected
   features, or user actions that trigger the issue.

3. **Synthesize**: Connect the quantitative data (stats) with qualitative evidence (samples)
   to identify the root cause and impact.

## Guidelines

- Be specific and evidence-based. Cite actual percentages and patterns you observe.
- If tickets are in German, translate the key points to English in your analysis.
- Focus on actionable insights, not just describing the data.
- Prioritize clarity over completeness - highlight the most important findings.
"""

